### ISSUE TITLE
Authentication Error on Github OAuth

### ISSUE THREAD

**Issue by elegantcoder** [spoqa/geofront#12]
I met the 400 bad request error while authenticating to github oauth, on v0.3.0

I found that it worked when changing `backends/github.py` to v0.2.2 version's one.

And I found this code changed some days ago: 
https://github.com/spoqa/geofront/commit/9db44659c423ed33a89de712fb645186b7c722cc

IMHO, `code` should be equal `req.args['code']`.

**Comment by dahlia** [comment]
Thanks for your report.  I will fix this soon.

**Comment by dahlia** [comment]
Fixed from [0.3.1][1].

[1]: https://pypi.python.org/pypi/Geofront/0.3.1
