### ISSUE TITLE
When will 0.4 release?

### ISSUE THREAD

**Issue by petecoop** [spoqa/geofront#13]
Hey I've noticed you've been working on 0.4, which includes OAuth integration which I'd really like to use, do you have an idea when you will be releasing 0.4?

**Comment by dahlia** [comment]
Unfortunately, I currently am not sure when the next released would be made.  If you want to use 0.4 right now you can use the master through `pip install git+git://github.com/spoqa/geofront.git` command.  It is quite stable so that we've used it for a while.

**Comment by petecoop** [comment]
Ah okay. If it's quite stable is there any reason to not release it?

**Comment by dahlia** [comment]
There are planned features that should be included in the next release. 😉

**Comment by petecoop** [comment]
Ah cool thanks 👍  I'll try the OAuth stuff with master
